version: '3'

services:
  mongodb:
    image: mongo:latest 
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: test
    hostname: mongodb

volumes:
  mongodb-data:
